Q: Show the names and addresses of customers 
located in the United States that 
have a credit limit of more than $100,000 

SELECT CUSTOMERNAME, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE
FROM CUSTOMERS
WHERE COUNTRY = 'USA' AND CREDITLIMIT > 100000;

Q: For each customer located in France, 
show the number of “Shipped” orders. 

SELECT CUSTOMERNAME, COUNT(*) AS Shipped_Orders
FROM CUSTOMERS
INNER JOIN ORDERS
		ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
WHERE COUNTRY = 'France' AND STATUS = 'Shipped'
GROUP BY CUSTOMERNAME;

Q: For each Product Line, 
show a count of the number of products and 
the average MSRP (ONLY SHOW the avg(MSRP) is more than $90)

SELECT TOP 1 PRODUCTLINES.PRODUCTLINE, COUNT(*) AS Product_Num, AVG(PRODUCTS.MSRP) AS Avg_MSRP
FROM PRODUCTS
INNER JOIN PRODUCTLINES
		ON PRODUCTS.PRODUCTLINE = PRODUCTLINES.PRODUCTLINE
GROUP BY PRODUCTLINES.PRODUCTLINE
HAVING AVG(PRODUCTS.MSRP) > 90;

Q: What is the product name, 
product line and MSRP of the most expensive product? 

SELECT TOP 1 PRODUCTNAME, PRODUCTLINE, MSRP
FROM PRODUCTS
ORDER BY BUYPRICE DESC;

Q: For each Sales rep working in the EMEA territory, 
show the customer name of customers who are 
in the same country as the sales rep

SELECT EMPLOYEES.FIRSTNAME, EMPLOYEES.LASTNAME, CUSTOMERS.CUSTOMERNAME
FROM (EMPLOYEES
INNER JOIN OFFICES
		ON EMPLOYEES.OFFICECODE = OFFICES.OFFICECODE) 
		INNER JOIN CUSTOMERS
				ON EMPLOYEES.EMPLOYEENUMBER = CUSTOMERS.SALESREPEMPLOYEENUMBER
WHERE OFFICES.COUNTRY = CUSTOMERS.COUNTRY AND OFFICES.TERRITORY = 'EMEA' AND EMPLOYEES.JOBTITLE = 'Sales Rep';

Q: Show the total order amount 
(quantity ordered * price each) for each customer 
located in Finland, Denmark or Sweden. 
Be sure to show the customer’s name and only include 
orders that have shipped. 

SELECT CUSTOMERS.CUSTOMERNAME, SUM(ORDERDETAILS.QUANTITYORDERED*ORDERDETAILS.PRICEEACH) AS Total_Order_Amount
FROM (ORDERDETAILS
INNER JOIN ORDERS
		ON ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
		INNER JOIN CUSTOMERS
				ON ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER
WHERE CUSTOMERS.COUNTRY IN ('Finland', 'Denmark', 'Sweden') AND ORDERS.STATUS = 'Shipped'
GROUP BY CUSTOMERS.CUSTOMERNAME;

Q:For each Sales Manager, 
show a count of the number of Sales reps. 
that report to them 

SELECT E1.EMPLOYEENUMBER, E1.LASTNAME, E1.FIRSTNAME,  
COUNT(E2.EMPLOYEENUMBER) AS Salesrep_Num
FROM EMPLOYEES E1
INNER JOIN EMPLOYEES E2
		ON E1.EMPLOYEENUMBER = E2.REPORTSTO  
WHERE (E1.JOBTITLE LIKE "*Manager*") AND (E2.JOBTITLE = "Sales Rep") 
GROUP BY E1.EMPLOYEENUMBER, E1.LASTNAME, E1.FIRSTNAME; 

Q: For each customer, 
show the net balance of 
total order amount vs. total payments

SELECT CUSTOMERS.CUSTOMERNUMBER, SUM(ORDERDETAILS.QUANTITYORDERED*ORDERDETAILS.PRICEEACH) AS Total_Order_Amount
FROM (ORDERDETAILS
INNER JOIN ORDERS
		ON ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
		INNER JOIN CUSTOMERS
				ON ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER
GROUP BY CUSTOMERS.CUSTOMERNUMBER;

WITH previous_result AS (
SELECT CUTOMERS.CUSTOMERNUMBER, SUM(ORDERDETAILS.QUANTITYORDERED*ORDERDETAILS.PRICEEACH) AS Total_Order_Amount
FROM (ORDERDETAILS
INNER JOIN ORDERS
		ON ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
		INNER JOIN CUSTOMERS
				ON ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER
GROUP BY CUSTOMERS.CUSTOMERNUMBER
)
SELECT PAYMENTS.CUSTOMERNUMBER, previous_result.Total_Order_Amount - SUM(AMOUNT)
FROM previous_result
INNER JOIN PAYMENTS
		ON previous_result.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER
GROUP BY PAYMENTS.CUSTOMERNUMBER;

-- Access does not support WITH function

SELECT CUSTOMERS_PAYMENTS.CUSTOMERNUMBER, 
	   CUSTOMERS_PAYMENTS.CUSTOMERNAME, 
	   (SUM(ORDERDETAILS.QUANTITYORDERED*ORDERDETAILS.PRICEEACH) - CUSTOMERS_PAYMENTS.Total_Payment) AS Total_Balance
FROM 
(
	(SELECT CUSTOMERS.CUSTOMERNUMBER, CUSTOMERS.CUSTOMERNAME, SUM(PAYMENTS.AMOUNT) AS Total_Payment
	FROM CUSTOMERS
	INNER JOIN PAYMENTS
			ON CUSTOMERS.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER
	GROUP BY CUSTOMERS.CUSTOMERNUMBER, CUSTOMERS.CUSTOMERNAME
	)	CUSTOMERS_PAYMENTS
	INNER JOIN ORDERS
				ON CUSTOMERS_PAYMENTS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
)
INNER JOIN ORDERDETAILS
		ON ORDERS.ORDERNUMBER = ORDERDETAILS.ORDERNUMBER
GROUP BY CUSTOMERS_PAYMENTS.CUSTOMERNUMBER, CUSTOMERS_PAYMENTS.CUSTOMERNAME, CUSTOMERS_PAYMENTS.Total_Payment;


